export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  ROOT: '/',
  DASHBOARD: '/dashboard',
  OBJECTS: '/objects',
  OBJECTS_CREATE: '/objects/create',
  OBJECT_EDIT: (objectId: string | number) => `/objects/${objectId}/edit`,
  OBJECT_PUBLIC: (objectId: string | number) => `/objects/${objectId}/public`,
  OBJECT_DETAIL: (objectId: string | number) => `/objects/${objectId}`,
  WORK_CREATE: (objectId: string | number) => `/objects/${objectId}/works/create`,
  WORK_DETAIL: (objectId: string | number, workId: string | number) => `/objects/${objectId}/works/${workId}`,
  ACTIVITY: '/activity',
  MY_WORKS: '/my-works',
  WORK_LOG: '/work-log',
  INSPECTION_DETAIL: (inspectionId: string | number) => `/inspection/${inspectionId}`,
  INSPECTION_DETAIL_ALT: (inspectionId: string | number) => `/inspections/${inspectionId}`,
  JOURNAL_ENTRY: (entryId: string | number) => `/journal-entry/${entryId}`,
  DEFECT_REPORT: (reportId: string | number) => `/defect-report/${reportId}`,
  DEFECTS: '/defects',
  DOCUMENTS: '/documents',
  DOCUMENT_VIEW: (id: string | number) => `/document/${id}`,
  DOCUMENT_NEW: '/document/new',
  ANALYTICS: '/analytics',
  CONTRACTORS: '/contractors',
  MESSAGES: '/messages',
  PROFILE: '/profile',
  PUBLIC_OBJECT: (objectId: string | number) => `/public/objects/${objectId}`,
  SETTINGS: '/settings',
  WORK_TEMPLATES: '/work-templates',
  ADMIN: '/admin',
  WORK_TYPES: '/work-types',
  MY_TASKS: '/my-tasks',
  PRICING: '/pricing',
  DOCUMENT_TEMPLATES: '/document-templates',
  DOCUMENT_TEMPLATE_EDITOR: (templateId: string | number) => `/document-templates/${templateId}`,
  ORGANIZATION: '/organization',
  CLIENT_ONBOARDING: '/onboarding',
  NOT_FOUND: '*'
} as const;

export const ROUTE_PATHS = {
  OBJECT_EDIT: '/objects/:objectId/edit',
  OBJECT_PUBLIC: '/objects/:objectId/public',
  OBJECT_DETAIL: '/objects/:objectId',
  WORK_CREATE: '/objects/:objectId/works/create',
  WORK_DETAIL: '/objects/:objectId/works/:workId',
  INSPECTION_DETAIL: '/inspection/:inspectionId',
  INSPECTION_DETAIL_ALT: '/inspections/:inspectionId',
  JOURNAL_ENTRY: '/journal-entry/:entryId',
  DEFECT_REPORT: '/defect-report/:reportId',
  DOCUMENT_VIEW: '/document/:id',
  PUBLIC_OBJECT: '/public/objects/:objectId',
  DOCUMENT_TEMPLATE_EDITOR: '/document-templates/:templateId'
} as const;