export const PRESET_TEMPLATES = {
  contract: {
    name: 'Договор',
    icon: 'FileText',
    schemas: [[
      {
        name: 'contract_number',
        type: 'text',
        position: { x: 150, y: 15 },
        width: 40,
        height: 8,
        fontSize: 10,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'contract_date',
        type: 'text',
        position: { x: 150, y: 25 },
        width: 40,
        height: 8,
        fontSize: 10,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'title',
        type: 'text',
        position: { x: 20, y: 45 },
        width: 170,
        height: 12,
        fontSize: 18,
        fontColor: '#000000',
        alignment: 'center',
      },
      {
        name: 'party_1_name',
        type: 'text',
        position: { x: 20, y: 70 },
        width: 170,
        height: 8,
        fontSize: 11,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'party_2_name',
        type: 'text',
        position: { x: 20, y: 85 },
        width: 170,
        height: 8,
        fontSize: 11,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'terms',
        type: 'text',
        position: { x: 20, y: 105 },
        width: 170,
        height: 100,
        fontSize: 10,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'signature_1',
        type: 'image',
        position: { x: 20, y: 220 },
        width: 60,
        height: 20,
      },
      {
        name: 'signature_2',
        type: 'image',
        position: { x: 130, y: 220 },
        width: 60,
        height: 20,
      },
    ]],
  },
  invoice: {
    name: 'Счёт',
    icon: 'Receipt',
    schemas: [[
      {
        name: 'invoice_number',
        type: 'text',
        position: { x: 20, y: 15 },
        width: 170,
        height: 10,
        fontSize: 14,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'invoice_date',
        type: 'text',
        position: { x: 20, y: 30 },
        width: 80,
        height: 8,
        fontSize: 10,
        fontColor: '#666666',
        alignment: 'left',
      },
      {
        name: 'seller_info',
        type: 'text',
        position: { x: 20, y: 50 },
        width: 85,
        height: 40,
        fontSize: 9,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'buyer_info',
        type: 'text',
        position: { x: 110, y: 50 },
        width: 85,
        height: 40,
        fontSize: 9,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'items_table',
        type: 'text',
        position: { x: 20, y: 100 },
        width: 170,
        height: 80,
        fontSize: 9,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'total_amount',
        type: 'text',
        position: { x: 130, y: 190 },
        width: 60,
        height: 12,
        fontSize: 14,
        fontColor: '#000000',
        alignment: 'right',
      },
      {
        name: 'qr_code',
        type: 'qrcode',
        position: { x: 165, y: 210 },
        width: 25,
        height: 25,
      },
    ]],
  },
  act: {
    name: 'Акт выполненных работ',
    icon: 'ClipboardCheck',
    schemas: [[
      {
        name: 'act_number',
        type: 'text',
        position: { x: 150, y: 15 },
        width: 40,
        height: 8,
        fontSize: 10,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'act_date',
        type: 'text',
        position: { x: 150, y: 25 },
        width: 40,
        height: 8,
        fontSize: 10,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'title',
        type: 'text',
        position: { x: 20, y: 45 },
        width: 170,
        height: 12,
        fontSize: 16,
        fontColor: '#000000',
        alignment: 'center',
      },
      {
        name: 'contractor',
        type: 'text',
        position: { x: 20, y: 70 },
        width: 170,
        height: 8,
        fontSize: 10,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'customer',
        type: 'text',
        position: { x: 20, y: 85 },
        width: 170,
        height: 8,
        fontSize: 10,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'work_description',
        type: 'text',
        position: { x: 20, y: 105 },
        width: 170,
        height: 90,
        fontSize: 10,
        fontColor: '#000000',
        alignment: 'left',
      },
      {
        name: 'contractor_signature',
        type: 'image',
        position: { x: 20, y: 210 },
        width: 60,
        height: 20,
      },
      {
        name: 'customer_signature',
        type: 'image',
        position: { x: 130, y: 210 },
        width: 60,
        height: 20,
      },
    ]],
  },
  certificate: {
    name: 'Сертификат',
    icon: 'Award',
    schemas: [[
      {
        name: 'certificate_title',
        type: 'text',
        position: { x: 20, y: 60 },
        width: 170,
        height: 15,
        fontSize: 24,
        fontColor: '#1e40af',
        alignment: 'center',
      },
      {
        name: 'recipient_name',
        type: 'text',
        position: { x: 20, y: 90 },
        width: 170,
        height: 20,
        fontSize: 20,
        fontColor: '#000000',
        alignment: 'center',
      },
      {
        name: 'description',
        type: 'text',
        position: { x: 30, y: 120 },
        width: 150,
        height: 60,
        fontSize: 12,
        fontColor: '#333333',
        alignment: 'center',
      },
      {
        name: 'date',
        type: 'text',
        position: { x: 20, y: 190 },
        width: 80,
        height: 10,
        fontSize: 10,
        fontColor: '#666666',
        alignment: 'left',
      },
      {
        name: 'signature',
        type: 'image',
        position: { x: 130, y: 185 },
        width: 60,
        height: 20,
      },
    ]],
  },
};
